### ISSUE TITLE
[BUG] Compatibility issue with plugins about class 'org.opensearch.action.support.master.AcknowledgedResponse'

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#3663]
**Describe the bug**
Similar issue: https://github.com/opensearch-project/OpenSearch/issues/3683 and https://github.com/opensearch-project/OpenSearch/issues/3688
Introduced by PR https://github.com/opensearch-project/OpenSearch/pull/3593 / commit https://github.com/opensearch-project/OpenSearch/commit/223d472e6d8ea4454cb05fba7271d213430a1a4e, which aims to resolve issue #3542

The change of class `org.opensearch.action.support.master.AcknowledgedResponse` causes compatibility issue with plugins that uses this class.

For example:
This is the code in security that causes build failure:
https://github.com/opensearch-project/security/blob/f431ec2201e1466b7c12528347a1f54cf64387c9/src/main/java/org/opensearch/security/tools/SecurityAdmin.java#L518

The problem is the variable definition is in type of a subclass, while an object in superclass is assigned to the variable.

The current `AcknowledgedResponse` in `master` package `extends` the same name class in `clustermanager` class
https://github.com/opensearch-project/OpenSearch/blob/223d472e6d8ea4454cb05fba7271d213430a1a4e/server/src/main/java/org/opensearch/action/support/master/AcknowledgedResponse.java
In the meantime, I changed the return value type of "putSettings" method to the class in "cluster manager" package.
While security plugin is using the `AcknowledgedResponse` class in `master` package.

**To Reproduce**
1. Build OpenSearch 2.1.0 Snapshot using the code https://github.com/opensearch-project/OpenSearch/tree/79cabafebc74e8379f7c854657693ca3b03a3247
2. Build security plugin or k-NN plugin with the above OpenSearch build artifact.
3. Plugins can't be built.

**Expected behavior**
The current plugins can be built correctly without making name change to OpenSearch Java API.

**Additional context**
A build failure in CCR plugin (comes from https://github.com/opensearch-project/cross-cluster-replication/pull/398):
`/home/runner/work/cross-cluster-replication/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/action/autofollow/TransportAutoFollowClusterManagerNodeAction.kt: (48, 1): Class 'TransportAutoFollowClusterManagerNodeAction' is not abstract and does not implement abstract base class member protected/*protected and package*/ abstract fun clusterManagerOperation(p0: AutoFollowClusterManagerNodeRequest!, p1: ClusterState!, p2: ActionListener<AcknowledgedResponse!>!): Unit defined in org.opensearch.action.support.master.TransportMasterNodeAction`

**Solution:**
Restore the change for this class to keep the compatibility.

To restore the class `org.opensearch.action.support.master.AcknowledgedResponse` to its original appearance (https://github.com/opensearch-project/OpenSearch/blob/2.0.1/server/src/main/java/org/opensearch/action/support/master/AcknowledgedResponse.java)
I need to do in 2 PRs to keep the git history of the file:
1. Remove the current class `AcknowledgedResponse` from `package org.opensearch.action.support.master`
2. Move the class `AcknowledgedResponse` from `package org.opensearch.action.support.clustermanager` to `org.opensearch.action.support.master` (https://github.com/opensearch-project/OpenSearch/blob/7005b9eb42f66912507b8f973b79734c260bdfe9/server/src/main/java/org/opensearch/action/support/clustermanager/AcknowledgedResponse.java)

**Comment by tlfeng** [comment]
The problem will be resolved for now after the backport PR https://github.com/opensearch-project/OpenSearch/pull/3670 merged.
I will think of the correct way to deal with the class `AcknowledgedResponse` and related classes.

**Comment by andrross** [comment]
Since Java doesn't really offer a clean way to change only the return type of a method in a non-breaking way, it's my opinion that we can probably do this as a breaking change. We'll have to proactively reach out to all the plugins in opensearch-project, but it should be as simple as a find-and-replace in the import statement, i.e. replace 

```
import org.opensearch.action.support.master.AcknowledgedResponse;
```

with

```
import org.opensearch.action.support.clustermanager.AcknowledgedResponse;
```

At a minimum we should identify all usages across all repos and open issues, or even just open PRs with the renamed import statement.

**Comment by tlfeng** [comment]
There are other 3 classes that have relationship with the class `AcknowledgedResponse`, they will likely be treated in the same way together. They all in the same package `org.opensearch.action.support.master`.
```
AcknowledgedRequest
AcknowledgedRequestBuilder
ShardsAcknowledgedResponse
```
Reason:
- ShardsAcknowledgedResonse
It's a subclass of `AcknowledgedResonse`.
https://github.com/opensearch-project/OpenSearch/blob/82ff463fd1bc07c241c8674b72182f2875a60425/server/src/main/java/org/opensearch/action/support/master/ShardsAcknowledgedResponse.java#L52

**Comment by tlfeng** [comment]
As mentioned above, the 4 classes `AcknowledgedRequest`, `AcknowledgedRequestBuilder`, `AcknowledgedResponse`, `ShardsAcknowledgedResponse` in package `org.opensearch.action.support.master` will not be deprecated in version `2.x`, and will be moved to package `org.opensearch.action.support.clustermanager` directly in a future major version as a breaking change.

**Comment by peternied** [comment]
@tlfeng How will these other deprecations be handled - is there an issue tracking them?

**Comment by andrross** [comment]
Resolving this issue again. The inclusive naming deprecation high level approach is detailed in the blog post here: https://opensearch.org/blog/technical-post/2022/10/Adopting-inclusive-language-across-OpenSearch/

**Comment by peternied** [comment]
@andrross I've created https://github.com/opensearch-project/OpenSearch/issues/4856 to track these classes that need to be moved as a breaking change.
