### ISSUE TITLE
[BUG] The non-core plugin test cases fail due to the use of JDK incubator features 

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#11937]
### Describe the bug

Caused by https://github.com/opensearch-project/OpenSearch/pull/11194

```
Caused by:                                                                                                                                                   
java.lang.NoClassDefFoundError: jdk/incubator/vector/LongVector                                                                                              
    at __randomizedtesting.SeedInfo.seed([D65A64F81C71BE2B]:0)                                                                                               
    at org.opensearch.common.round.RoundableFactory.<clinit>(RoundableFactory.java:39)                                                                       
    at org.opensearch.common.Rounding$PreparedRounding.maybeUseArray(Rounding.java:454)                                        
    at org.opensearch.common.Rounding$TimeUnitRounding.prepare(Rounding.java:569)                                             
    at org.opensearch.search.aggregations.support.CoreValuesSourceType$7$1.lambda$roundingPreparer$0(CoreValuesSourceType.java:401)                          
    at org.opensearch.search.aggregations.bucket.histogram.DateHistogramAggregatorFactory.doCreateInternal(DateHistogramAggregatorFactory.java:113)       
    at org.opensearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:76)
    at org.opensearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:103)                                                               
    at org.opensearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:315)                                        
    at org.opensearch.search.aggregations.AggregatorFactories.createTopLevelNonGlobalAggregators(AggregatorFactories.java:301)                               
    at org.opensearch.search.aggregations.AggregationCollectorManager.newCollector(AggregationCollectorManager.java:45)                                      
    at org.opensearch.search.aggregations.NonGlobalAggCollectorManagerWithSingleCollector.<init>(NonGlobalAggCollectorManagerWithSingleCollector.java:33)    
    at org.opensearch.search.aggregations.DefaultAggregationProcessor.preProcess(DefaultAggregationProcessor.java:37)                                        
    at org.opensearch.search.query.QueryPhase.execute(QueryPhase.java:154)                                                                                   
    at org.opensearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:546)                                                                   
    at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:610)                                                                         
    at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:579)                                                                     
    at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:74)                                                                          
    at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:89)                                                                                  
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)                                                                  
    at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)                                                                       
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)                                                                  
    at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:59)                                                                      
    at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913)                                   
    at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)                                                                  
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)                                                             
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)                                                             
    at java.base/java.lang.Thread.run(Thread.java:1583)                                                                                                      
                                                                                                                                                             
    Caused by:                                                                                                                                               
    java.lang.ClassNotFoundException: jdk.incubator.vector.LongVector                                                                                        
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)                                                           
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)                                                        
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)                                                                                   
        ... 27 more    
```

### Related component

Plugins

### To Reproduce

Run any plugin test suite

### Expected behavior

The build shouldn't fail

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**
