### PR TITLE
Add deprecated API for creating History Ops Snapshot from translog

### PR DESCRIPTION
**Pull request by saikaranam-amazon**
Signed-off-by: Nicholas Walter Knize <nknize@apache.org>
Signed-off-by: Sai Kumar <karanas@amazon.com>

### Description
Adds a deprecated API to create a history operations snapshot from the translog.
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/2482
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
I want to make sure we all agree with the [complete proposal](https://github.com/opensearch-project/OpenSearch/issues/2482#issuecomment-1097037679), especially that we will be doing https://github.com/opensearch-project/OpenSearch/issues/2872 for 2.1+ (refactoring CCR as a core module), before merging this.

**Comment by dblock** [comment]
start gradle check

**Comment by saikaranam-amazon** [comment]
Failed test case -

```
> Task :client:rest-high-level:asyncIntegTest

REPRODUCE WITH: ./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.opensearch.client.IndicesClientIT.testPutTemplateWithDeprecatedTemplateField" -Dtests.seed=1708D43D2AEEB3A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=de-AT -Dtests.timezone=SystemV/EST5 -Druntime.java=17

org.opensearch.client.IndicesClientIT > testPutTemplateWithDeprecatedTemplateField FAILED
    org.opensearch.client.WarningFailureException: method [PUT], host [http://[::1]:41543], URI [/_template/my-template?master_timeout=30s], status line [HTTP/1.1 200 OK]
    Warnings: [Parameter [master_timeout] is deprecated and will be removed in 3.0. To support inclusive language, please use [cluster_manager_timeout] instead., Deprecated field [template] used, replaced by [index_patterns]]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([1708D43D2AEEB3A:1B8DC88B8EC245FA]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient$1.completed(RestClient.java:400)
        at app//org.opensearch.client.RestClient$1.completed(RestClient.java:396)
        at app//org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
        at app//org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
        at app//org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
        at app//org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
        at app//org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at app//org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at app//org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at app//org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at app//org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at app//org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at app//org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at app//org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
```

**Comment by tlfeng** [comment]
Hi @saikaranam-amazon Please ignore this test failure, which has been fixed in https://github.com/opensearch-project/OpenSearch/commit/455fad34eea2cb6d606f54a41ef170066b87b04e . The deprecation message in the test was changed by mistake.

**Comment by saikaranam-amazon** [comment]
@tlfeng Got it! thanks!

**Comment by saikaranam-amazon** [comment]
other failures
```
> Task :server:javadoc
/var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/server/src/main/java/org/opensearch/index/engine/Engine.java:748: error: unknown tag: Deprecated
     * @Deprecated reading history operations from the translog file is deprecated and will be removed in the next release
       ^
/var/CITOOL/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/search/server/src/main/java/org/opensearch/index/shard/IndexShard.java:2246: error: unknown tag: Deprecated
     * @Deprecated reading history operations from the translog file is deprecated and will be removed in the next release
       ^
/var/CITOOL/workflow/
```


Addressed in the latest revision

**Comment by saikaranam-amazon** [comment]
Please add the `backport` label to merge to 2.0 branch.

**Comment by saikaranam-amazon** [comment]
> I want to make sure we all agree with the https://github.com/opensearch-project/OpenSearch/issues/2482#issuecomment-1097037679, especially that we will be doing https://github.com/opensearch-project/OpenSearch/issues/2872 for 2.1+ (moving CCR into core module so we can refactor the deprecated methods into CCR in 2.1), before merging this.

Agreed and updated the issue - https://github.com/opensearch-project/OpenSearch/issues/2482

**Review by nknize — APPROVED** [review]
approve w/ reservations.

**Comment by saikaranam-amazon** [comment]
Thanks @nknize ! Could you please merge the PR? 
 - I don't have access

**Comment by dblock** [comment]
I merged and labeled to backport to 2.x as well
