### ISSUE TITLE
[BUG] Could not initialize class org.opensearch.common.xcontent.json.JsonXContent after updating from 2.11.1 to 2.12.0

### ISSUE THREAD

**Issue by acnolan** [opensearch-project/OpenSearch#12950]
### Describe the bug

After updating from OpenSearch version 2.11.1 to 2.12.0 my code now produces the following error:

`java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.common.xcontent.json.JsonXContent`

This is in a Java Springboot app. I am using Maven for package management and updated no other dependencies besides this one.

I did not see any required dependency changes or deprecations in the release notes for this version.

### Related component

Other

### To Reproduce

The following is a simplified version of the code I am using. Additional parameters are set on the searchRequest and searchSource.

```
SearchRequest searchRequest = searchRequest();
SearchSourceBuilder searchSource = searchSource();
restHighLevelClient.search(searchRequest.source(searchSource), RequestOptions.DEFAULT)
```

Within the RestHighLevelClient search method the error is thrown
> java.lang.NoClassDefFoundError: Could not initialize class org.opensearch.common.xcontent.json.JsonXContent

### Expected behavior

The code should execute without throwing an error, as it does with 2.11.1.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by cwperks** [comment]
Do you have `jar -tf lib/opensearch-x-content-2.12.1-SNAPSHOT.jar` on the classpath? I just pulled the latest on the 2.12 branch, created a local distribution and I can see this class in the jar.

```
➜  opensearch-2.12.1-SNAPSHOT git:(2.12) ✗ jar -tf lib/opensearch-x-content-2.12.1-SNAPSHOT.jar
...
org/opensearch/common/xcontent/json/JsonXContent.class
...
```

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/vikasvb90
) [4](https://github.com/andrross
) [5](https://github.com/lukas-vlcek/
) [6](https://github.com/srikanthpadakanti)]
@acnolan Thanks for creating this issue

**Comment by acnolan** [comment]
Thanks for your help looking into this. I see the class in my classpath and in IntelliJ I can see it in the external library browser for my project. It is strange, if I downgrade to older versions of OpenSearch like 2.10.0 or 2.11.0 it works as expected. But 2.12.0 or the new 2.13.0 do not seem to be working for me.

I will look into it a little more to see if something is wrong in my project structure as well.

**Comment by acnolan** [comment]
Hi! I can't believe I opened this a month ago, time flies. However, we can close this ticket now. I found a solution.

I needed to update the Liquibase dependency in my POM from 4.26.0 to 4.27.0. I am not sure why this fixed the issue but that was the only change needed to get it working again.

Closing with this comment so others with similar issues may see it.

**Comment by pmioulet** [comment]
I had the same issue with Springboot 2.2.X. Issue is in fact linked to the version of jackson. openseach above 2.12 has a minimal requirement of jackson 2.16. Springboot 2.2 ships with 2.14. I suspect the static initialisation in JsonXContent class fails silently due to a missing configuration parameter in older jackson versions. I did not investigate further to see which parameter is missing.

Hope this note helps anyone else facing the issue :)
