### ISSUE TITLE
[BUG] Invalid javadoc in PaginationStrategy class prevents OpenSearch compiling with javadocs

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/OpenSearch#16374]
### Describe the bug

The [PaginationStrategy](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java) class has javadoc errors using `@param` inline in three places:
https://github.com/opensearch-project/OpenSearch/blob/4456d559a425271fb35e8d4fb1a000ceb1e2e273/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java#L48

https://github.com/opensearch-project/OpenSearch/blob/4456d559a425271fb35e8d4fb1a000ceb1e2e273/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java#L60

These prevent a Gradle compile task from completing successfully without warning-mode disabled.

### Related component

Other

### To Reproduce

1. In a GitHub action, Checkout OpenSearch and assemble. 
   - See https://github.com/opensearch-project/opensearch-sdk-py/blob/main/.github/workflows/integration.yml
2. Observe compile failure
   - See log failure https://github.com/opensearch-project/opensearch-sdk-py/actions/runs/11285845602/job/31389275760
```
/home/runner/work/opensearch-sdk-py/opensearch-sdk-py/opensearch/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java:48: error: no tag name after @
     * Utility method to get list of indices filtered as per {@param filterPredicate} and the sorted according to {@param comparator}.
                                                             ^
/home/runner/work/opensearch-sdk-py/opensearch-sdk-py/opensearch/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java:48: error: no tag name after @
     * Utility method to get list of indices filtered as per {@param filterPredicate} and the sorted according to {@param comparator}.
                                                                                                                  ^
/home/runner/work/opensearch-sdk-py/opensearch-sdk-py/opensearch/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java:60: error: no tag name after @
     * Utility method to get list of indices sorted as per {@param comparator}.
                                                           ^

...

FAILURE: Build completed with 2 failures.
> Task :server:compileJava FAILED

110 actionable tasks: 110 executed
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':server:compileJava'.
> Compilation failed; see the compiler error output for details.
```

### Expected behavior

OpenSearch compiles without javadoc errors.

### Additional Details

**Additional context**

This does not appear on OpenSearch because these javadoc errors are suppressed in `gradle.properties`:
https://github.com/opensearch-project/OpenSearch/blob/4456d559a425271fb35e8d4fb1a000ceb1e2e273/gradle.properties#L14

However, this configuration is not used in other project GHA.  It can be worked around by using `--warning-mode none` switch on gradle commands, but it's better to not require projects to ignore these errors to compile.

Bug introduced in https://github.com/opensearch-project/OpenSearch/pull/14641 

CC: @gargharsh3134 @shwetathareja @rajiv-kv @vikasvb90

**Comment by skull-squadron** [comment]
Yep. main doesn't build and neither does [2.17.1](https://github.com/opensearch-project/OpenSearch/releases/tag/2.17.1).

**Comment by gargharsh3134** [comment]
@dbwiddis @skull-squadron Sorry, somehow missed this issue earlier. I'll raise a fix to address this, but at the time of merging, I remember couple of places were already using such inline javadocs, not sure if those too have been fixed.
Anyway, until fix is merged, can you please try to build using JDK 17 and above? It works on my local.
Thanks!

**Comment by gargharsh3134** [comment]
Raised a fix -> https://github.com/opensearch-project/OpenSearch/pull/16428
