### ISSUE TITLE
[BUG] Cluster goes down after upgrade to 2.1.0 (and then to 2.2.0)

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/OpenSearch#4203]
**Describe the bug**
After upgrading my three nodes Docker cluster to version 2.1.0, the nodes started to go down with the following error:

```
[2022-08-12T10:04:22,455][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [elastic-01] fatal error in thread [opensearch[elastic-01][generic][T#78]], exiting
	at org.opensearch.enrich.EnrichPolicyMaintenanceService.cleanUpEnrichIndices(EnrichPolicyMaintenanceService.java:135) ~[?:?]
	at org.opensearch.enrich.EnrichPolicyMaintenanceService.maybeCleanUpEnrichIndices(EnrichPolicyMaintenanceService.java:123) ~[?:?]
	at org.opensearch.enrich.EnrichPolicyMaintenanceService.execute(EnrichPolicyMaintenanceService.java:114) ~[?:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) ~[opensearch-2.2.0.jar:2.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
fatal error in thread [opensearch[elastic-01][generic][T#78]], exiting
	at java.lang.Thread.run(Thread.java:833) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
java.lang.NoSuchMethodError: 'org.opensearch.action.support.master.info.ClusterInfoRequest org.opensearch.action.admin.indices.get.GetIndexRequest.indices(java.lang.String[])'
```
I then updated to 2.2.0 and the same error happened

**To Reproduce**
1. Deploy Opensearch cluster with three nodes and with at least version 2.1.0 (or 2.2.0)
2. Wait some time (from minutes up to one hour)
3. See error

**Expected behavior**
The cluster should not go down

**Host/Environment (please complete the following information):**
Docker Cluster with version 2.2.0
(First time error raised was on version 2.1.0)

**Comment by andrross** [comment]
Hey @pietrogu, what is `org.opensearch.enrich.EnrichPolicyMaintenanceService`? There has been some refactoring of internal classes in OpenSearch core that were never intended to be used/extended by plugins, but unfortunately there was no strict enforcement. This looks likes a case where `org.opensearch.enrich.EnrichPolicyMaintenanceService` is using something that has been renamed to use the `clustermanager` namespace.

**Comment by pietrogu** [comment]
Ok, is there a way to solve the problem?

**Comment by dblock** [comment]
@pietrogu What version are you upgrading *from*?

**Comment by pietrogu** [comment]
I upgraded from 2.0.1 to 2.1.0
At this point I received the error
Then when available I updated to 2.2.0

**Comment by dblock** [comment]
@tlfeng should we restore that interface in 2.x?

**Comment by tlfeng** [comment]
@dblock There was a deprecation made in issue https://github.com/opensearch-project/OpenSearch/issues/3542, the idea is to keep all backwards compatibility of the existing Java APIs, including `org.opensearch.action.support.master.info.ClusterInfoRequest`. If this problem shows that `GetIndexRequest.indices(java.lang.String[])` is not accessible from the class, then I've made a mistake to break the compatibility, definitely I need to restore the API.

**Comment by andrross** [comment]
> Honestly, I don't know this details about the EnrichPolicyMaintenanceService location :(

@pietrogu We can restore compatibility in 2.x, but this _will_ break in 3.0 when we will fully remove the non-inclusive language from the code base, so you will have to update EnrichPolicyMaintenanceService eventually.

**Comment by dblock** [comment]
> @dblock There was a deprecation made in issue #3542, the idea is to keep all backwards compatibility of the existing Java APIs, including `org.opensearch.action.support.master.info.ClusterInfoRequest`. If this problem shows that `GetIndexRequest.indices(java.lang.String[])` is not accessible from the class, then I've made a mistake to break the compatibility, definitely I need to restore the API.

Do you want to take it?

**Comment by pietrogu** [comment]
Hi all,

thank you for the quick reply :)

So, If I understood well, after @tlfeng fix the problem should be resolved for now, but some changes need to be done on my side in my custom plugin before the 3.0 release?

**Comment by pietrogu** [comment]
Ok. I'll wait for the fix  by @tlfeng to close the issue.

Thank you

**Comment by tlfeng** [comment]
Hi @pietrogu I have made a fix for the backwards compatibility issue you pointed out. The fix have been merged into `main` branch (commit https://github.com/opensearch-project/OpenSearch/commit/65f966ed71ff9bc0a53490ee801943869c0f536d) and `2.x` branch (commit https://github.com/opensearch-project/OpenSearch/commit/7a0ee0859f802b7eaf4352ca53124a7a465367b9), which means it will be available in version 2.3 and above.
According to the release schedule (https://www.opensearch.org/releases.html), version 2.3 will be released on Sept.14th, 2022. Please have a try with OpenSearch version 2.3, and re-open the issue if you still face the same problem. Thank you!
